### ISSUE TITLE
First execution dropped an AttributeError

### ISSUE THREAD

**Issue by eldraco** [krmaxwell/maltrieve#141]
After installing all the dependencies, first execution on debian 32bits, non-privileged user.
commit 857508aa8556fbafc8112295599f5903e990e871

./maltrieve.py 
Processing source URLs
Completed source processing
Traceback (most recent call last):
  File "./maltrieve.py", line 512, in <module>
    main()
  File "./maltrieve.py", line 487, in main
    if cfg.inputfile:
AttributeError: 'config' object has no attribute 'inputfile'

**Comment by krmaxwell** [comment]
repro'ed

**Comment by krmaxwell** [comment]
@eldraco Can you try this hotfix and let me know if it works for you? Thanks for the report!

**Comment by eldraco** [comment]
Perfect! thanks a lot. Now is working.
