### ISSUE TITLE
Question: remember downloaded binaries

### ISSUE THREAD

**Issue by eldraco** [krmaxwell/maltrieve#147]
Does it remember the binaries that it already downloaded from the sites so it does not download them again?

**Comment by krmaxwell** [comment]
It remembers the URLs previously downloaded and the hashes. If the same file exists at a different URL, it won't know that until it downloads it (but when it does it will see we already have the hash). And it doesn't download the same URL twice.

See `urls.json` and `hashes.json` for more (although the implementation may change in a future update).
