### ISSUE TITLE
Feature Request: Proxy Credentials

### ISSUE THREAD

**Issue by mlawsonis** [krmaxwell/maltrieve#155]
Configuration for optional use of User Name and Password for proxy authentication. 

Thank you for all the work you've done.

**Comment by krmaxwell** [comment]
As long as it's Basic Auth, this is definitely doable. If you need Digest Auth for the proxy, that will take a bit more work.

**Comment by krmaxwell** [comment]
So it looks like we should already support this because we use [Requests](http://docs.python-requests.org/en/latest/user/advanced/#proxies):
> To use HTTP Basic Auth with your proxy, use the http://user:password@host/ syntax:

``` python
proxies = {
    "http": "http://user:pass@10.10.1.10:3128/",
}
```

I will note this in the documentation, though!
