### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mlawsonis** [krmaxwell/maltrieve#160]
Getting this error. When testing my cron job. I'm wondering if this is a environment variable I haven't set. These seemed to work fine for me a previous builds.  

shellprompt@ubuntu:~$ sudo python /home/shellprompt/Maltrieve/maltrieve.py
[sudo] password for shellprompt: 
Traceback (most recent call last):
  File "/home/shellprompt/Maltrieve/maltrieve.py", line 514, in <module>
    main()
  File "/home/shellprompt/Maltrieve/maltrieve.py", line 460, in main
    cfg = config(args, 'maltrieve.cfg')
  File "/home/shellprompt/Maltrieve/maltrieve.py", line 49, in __init__
    if args.logfile or self.configp.get('Maltrieve', 'logfile'):
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Maltrieve'

**Comment by krmaxwell** [comment]
Make sure the working directory for the script has `maltrieve.cfg` in it. You might just need to prepend the script invocation with a cd, something like
```
cd /home/maltrieve && ./maltrieve.py
```
(if your script and config are in `/home/maltrieve`).

**Comment by krmaxwell** [comment]
Did this work for you?

**Comment by mlawsonis** [comment]
Yes, thank you.
