### ISSUE TITLE
Getting AttributeError: object has no attribute 'description'

### ISSUE THREAD

**Issue by jebelingmi** [krmaxwell/maltrieve#163]
External sites see 68.40.253.188

Processing source URLs
Completed source processing
Traceback (most recent call last):
  File "/home/jeff/maltrieve/maltrieve.py", line 352, in <module>
    main()
  File "/home/jeff/maltrieve/maltrieve.py", line 322, in main
    malware_urls.update(source_urls[response.url](response.text))
  File "/home/jeff/maltrieve/maltrieve.py", line 145, in process_xml_list_desc
    desc = entry.description
  File "build/bdist.linux-x86_64/egg/feedparser.py", line 416, in __getattr__
AttributeError: object has no attribute 'description'

Tried updating feedparser

jeff@ubuntu64:~/maltrieve$ sudo easy_install feedparser
Searching for feedparser
Best match: feedparser 5.1.3
Processing feedparser-5.1.3-py2.7.egg
feedparser 5.1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/feedparser-5.1.3-py2.7.egg
Processing dependencies for feedparser
Finished processing dependencies for feedparser

Running Ubuntu 14.04 April 9th was last day it worked

**Comment by krmaxwell** [comment]
What version of Maltrieve are you running? And can you paste the output of `pip freeze`?

**Comment by jebelingmi** [comment]
How can I tell what version? I made the modification to correct issue with "key error u'http" on whatever version I was running. Going to try downloading latest. Can I just m.	sudo git clone https://github.com/technoskald/maltrieve.git ?

CDDB==1.4
Cython==0.22
GnuPGInterface==0.3.2
PAM==0.4.2
Pillow==2.3.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
beautifulsoup4==4.3.2
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
debtagshw==0.1
defer==1.0.6
dirspec==13.10
feedparser==5.1.3
gevent==1.0.1
greenlet==0.4.5
grequests==0.2.0
html5lib==0.999
httplib2==0.8
lxml==3.3.3
mutagen==1.22
oauthlib==0.6.1
oneconf==0.3.7
pexpect==3.1
piston-mini-client==0.7.5
psutil==1.2.1
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pygobject==3.12.0
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
python-magic==0.4.6
pyxdg==0.25
reportlab==3.0
requests==2.2.1
sessioninstaller==0.0.0
six==1.5.2
software-center-aptd-plugins==0.0.0
system-service==0.1.6
unity-lens-photos==1.0
urllib3==1.7.1
wsgiref==0.1.2
zope.interface==4.0.5

**Comment by jebelingmi** [comment]
Updated to latest version and made the change to remove the key error and working now thanks!

**Comment by krmaxwell** [comment]
What KeyError were you getting, and what change did you have to make?

**Comment by jebelingmi** [comment]
Same one listed in the recent bug. Had to change entry for vxvault to vxvault.net
