### ISSUE TITLE
Updated code breaks CRITs integration 

### ISSUE THREAD

**Issue by webstergd** [krmaxwell/maltrieve#164]
The updated code for the configuration object and domain logging breaks the integration. 
  - removal of verify causes a connection refusal when submitting domains. 
  - the configuration object parses crits URL incorrectly and returns either a true of false value verses the URL. 

I am testing a patch and will submit a pull request shortly.

**Comment by krmaxwell** [comment]
Hrm, that's odd since I'm running the code and it's uploading correctly to my CRITs instance. Wonder what's different.

**Comment by webstergd** [comment]
-            self.crits = args.crits or self.configp.get('Maltrieve', 'crits')
+            self.crits = self.configp.get('Maltrieve', 'crits')

In my setup that caused self.crits to be equal to True

-            domain_response = requests.post(url, headers=headers, data=domain_data)
+            domain_response = requests.post(url, headers=headers, data=domain_data, verify=False)

For some reason without that verify it breaks. Check your setup and look at domains and relationships. It will upload the samples but fails on the domain and creating the relationship. (I am using a valid ssl)

**Comment by krmaxwell** [comment]
Fixed in #165
