### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jwils0n0x** [krmaxwell/maltrieve#166]
when running maltrieve.py from ubuntu 14.04 (2.7.6 python, all dependencies and the like from requirements, etc.).  

I am executing the following command:  'python maltrieve.py -d ../somepath/ -l ../somepath/somelog -s'

I get the following dump after a few minutes of maltrieve churning:

Processing source URLs
Completed source processing
Traceback (most recent call last):
     File "maltrieve.py", line 514, in <module>
        main()
     File "maltrieve.py", line 487, in main
        malware_urls.update(source_urls[response.url](response.text))
KeyError: u'http://vxvault.net//URL_List.php'

**Comment by krmaxwell** [comment]
This was fixed in f969a5f which I've just merged to master. Please update to the newest code - that should do it.

**Comment by jwils0n0x** [comment]
Confirmed fixed for me.  Thanks!

**Comment by krmaxwell** [comment]
Thanks for the reminder!
