### ISSUE TITLE
Document use via crontab

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/maltrieve#76]
Provide sample crontab entry and solutions to common problems

**Comment by krmaxwell** [comment]
This is the perfect thing for somebody who wants to write some docs without having to dodge code...

**Comment by webstergd** [comment]
Hey do you still need someone to document how to do this? If so i will knock it out for you real fast.

**Comment by krmaxwell** [comment]
Feel free, I haven't quite gotten to it yet and anything that shortens time to v0.7 is good :grinning:

**Comment by krmaxwell** [comment]
Fixed in dbe8812
