### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Healwhans** [krmaxwell/maltrieve#87]
Maltrieve started throwing an error after execution as a regular user.

>:/opt/maltrieve$ python maltrieve.py
>Traceback (most recent call last):
>  File "maltrieve.py", line 336, in <module>
>    main()
>  File "maltrieve.py", line 281, in main
>    past_urls = json.load(urlfile)
>  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
>    **kw)
>  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>    return _default_decoder.decode(s)
>  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
>    raise ValueError("No JSON object could be decoded")
>ValueError: No JSON object could be decoded

Thanks Kyle!!!
-Heal

**Comment by krmaxwell** [comment]
Two things:

1. You have an older version and might want to upgrade when you get a chance. No biggie, I don't think.
2. For your specific question - what does your `urls.json` file look like?

**Comment by Healwhans** [comment]
`urls.json` is empty.

**Comment by Healwhans** [comment]
After downloading the newer version of maltrieve, the error went away. Thanks for your help.
