### ISSUE TITLE
 How are versions identified in the maltrieve.py file?

### ISSUE THREAD

**Issue by Healwhans** [krmaxwell/maltrieve#94]
In my previous comment I wanted to include the version number of maltrieve. There wasn't a version in the header of the Python file.

**Comment by krmaxwell** [comment]
As of v0.6 (just released), you can see the version in `setup.py`. I'm working on stuff for v0.7 now that will focus on architecture and engineering, at which point it'll be more obvious to users and developers.

**Comment by Healwhans** [comment]
IDK why but the versions I've downloaded from the maltrieve website do not include `setup.py`. I'm closing this issue because the question has been answered.
Thanks!

**Comment by krmaxwell** [comment]
That's because that's just in v0.6 as mentioned. :)

**Comment by Healwhans** [comment]
Can you tell I don't read? I skim. Gets me in all sorts of trouble... :0) Thanks for your hard work keeping maltrieve current!
